# Generated by Django 5.1.6 on 2025-03-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='EXIT', upload_to='products/'),
            preserve_default=False,
        ),
    ]
