# Generated by Django 5.1.6 on 2025-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='exit', upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
